import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, writeFileSync, rmSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import type { PreToolUseHookInput } from "@anthropic-ai/claude-code";
import { isGeneratedFile, processInput } from "./check.ts";

function mockInput(filePath: string): PreToolUseHookInput {
  return {
    hook_event_name: "PreToolUse",
    session_id: "test",
    transcript_path: "/tmp/test",
    cwd: "/tmp",
    tool_name: "Edit",
    tool_input: { file_path: filePath },
  };
}

describe("isGeneratedFile", () => {
  it("returns false for files without generated marker", () => {
    const content = `package main

func main() {
    println("hello")
}`;
    expect(isGeneratedFile(content)).toBe(false);
  });

  it("returns true for files with generated marker before code", () => {
    const content = `// Code generated by foo. DO NOT EDIT.

package main

func main() {
    println("generated")
}`;
    expect(isGeneratedFile(content)).toBe(true);
  });

  it("returns false for files with marker after code", () => {
    const content = `package main

// Code generated by foo. DO NOT EDIT.
func main() {
    println("not generated")
}`;
    expect(isGeneratedFile(content)).toBe(false);
  });

  it("returns false for files with only marker and no code", () => {
    const content = `// Code generated by foo. DO NOT EDIT.


`;
    expect(isGeneratedFile(content)).toBe(false);
  });

  it("returns true for files with marker and blank lines before code", () => {
    const content = `// Code generated automatically. DO NOT EDIT.


package main`;
    expect(isGeneratedFile(content)).toBe(true);
  });
});

describe("processInput", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "go-hook-test-"));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it("allows non-Go files", () => {
    const filePath = join(tempDir, "test.txt");
    writeFileSync(filePath, "some content");
    const output = processInput(mockInput(filePath));
    expect(output).toBeNull();
  });

  it("allows Go files without generated marker", () => {
    const filePath = join(tempDir, "main.go");
    writeFileSync(
      filePath,
      `package main

func main() {
    println("hello")
}`
    );
    const output = processInput(mockInput(filePath));
    expect(output).toBeNull();
  });

  it("allows non-existent Go files", () => {
    const filePath = join(tempDir, "nonexistent.go");
    const output = processInput(mockInput(filePath));
    expect(output).toBeNull();
  });

  it("blocks Go files with generated marker", () => {
    const filePath = join(tempDir, "generated.go");
    writeFileSync(
      filePath,
      `// Code generated by foo. DO NOT EDIT.

package main

func main() {
    println("generated")
}`
    );
    const output = processInput(mockInput(filePath));
    expect(output).toEqual({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `Cannot modify generated Go file: ${filePath}`,
      },
    });
  });

  it("allows Go files with marker after code", () => {
    const filePath = join(tempDir, "not-generated.go");
    writeFileSync(
      filePath,
      `package main

// Code generated by foo. DO NOT EDIT.
func main() {
    println("not generated")
}`
    );
    const output = processInput(mockInput(filePath));
    expect(output).toBeNull();
  });

  it("blocks Go files with marker before package declaration", () => {
    const filePath = join(tempDir, "proto.go");
    writeFileSync(
      filePath,
      `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

type Test struct {}`
    );
    const output = processInput(mockInput(filePath));
    expect(output).toEqual({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `Cannot modify generated Go file: ${filePath}`,
      },
    });
  });

  it("allows Go files with only marker and no code", () => {
    const filePath = join(tempDir, "marker-only.go");
    writeFileSync(
      filePath,
      `// Code generated by foo. DO NOT EDIT.


`
    );
    const output = processInput(mockInput(filePath));
    expect(output).toBeNull();
  });

  it("blocks Go files with marker and blank lines before code", () => {
    const filePath = join(tempDir, "blanks.go");
    writeFileSync(
      filePath,
      `// Code generated automatically. DO NOT EDIT.


package main`
    );
    const output = processInput(mockInput(filePath));
    expect(output).toEqual({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `Cannot modify generated Go file: ${filePath}`,
      },
    });
  });
});
