import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync } from "node:fs";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { PreToolUseHookInput } from "@anthropic-ai/claude-agent-sdk";
import { isGeneratedFile, processInput } from "./check";

function mockInput(filePath: string): PreToolUseHookInput {
  return {
    hook_event_name: "PreToolUse",
    session_id: "test",
    transcript_path: "/tmp/test",
    cwd: "/tmp",
    tool_name: "Edit",
    tool_input: { file_path: filePath },
    tool_use_id: "test",
  };
}

describe("isGeneratedFile", () => {
  test.each<{ name: string; content: string; expected: boolean }>([
    {
      name: "returns false for files without generated marker",
      content: `package main

func main() {
    println("hello")
}`,
      expected: false,
    },
    {
      name: "returns true for files with generated marker before code",
      content: `// Code generated by foo. DO NOT EDIT.

package main

func main() {
    println("generated")
}`,
      expected: true,
    },
    {
      name: "returns false for files with marker after code",
      content: `package main

// Code generated by foo. DO NOT EDIT.
func main() {
    println("not generated")
}`,
      expected: false,
    },
    {
      name: "returns false for files with only marker and no code",
      content: `// Code generated by foo. DO NOT EDIT.


`,
      expected: false,
    },
    {
      name: "returns true for files with marker and blank lines before code",
      content: `// Code generated automatically. DO NOT EDIT.


package main`,
      expected: true,
    },
  ])("$name", ({ content, expected }) => {
    expect(isGeneratedFile(content)).toBe(expected);
  });
});

describe("processInput", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "go-hook-test-"));
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  test.each<{
    name: string;
    fileName: string;
    content?: string;
    blocked: boolean;
  }>([
    {
      name: "allows non-Go files",
      fileName: "test.txt",
      content: "some content",
      blocked: false,
    },
    {
      name: "allows Go files without generated marker",
      fileName: "main.go",
      content: `package main

func main() {
    println("hello")
}`,
      blocked: false,
    },
    {
      name: "allows non-existent Go files",
      fileName: "nonexistent.go",
      blocked: false,
    },
    {
      name: "blocks Go files with generated marker",
      fileName: "generated.go",
      content: `// Code generated by foo. DO NOT EDIT.

package main

func main() {
    println("generated")
}`,
      blocked: true,
    },
    {
      name: "allows Go files with marker after code",
      fileName: "not-generated.go",
      content: `package main

// Code generated by foo. DO NOT EDIT.
func main() {
    println("not generated")
}`,
      blocked: false,
    },
    {
      name: "blocks Go files with marker before package declaration",
      fileName: "proto.go",
      content: `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

type Test struct {}`,
      blocked: true,
    },
    {
      name: "allows Go files with only marker and no code",
      fileName: "marker-only.go",
      content: `// Code generated by foo. DO NOT EDIT.


`,
      blocked: false,
    },
    {
      name: "blocks Go files with marker and blank lines before code",
      fileName: "blanks.go",
      content: `// Code generated automatically. DO NOT EDIT.


package main`,
      blocked: true,
    },
  ])("$name", async ({ fileName, content, blocked }) => {
    const filePath = join(tempDir, fileName);
    if (content !== undefined) {
      await Bun.write(filePath, content);
    }
    const output = await processInput(mockInput(filePath));
    expect(output).toEqual(
      blocked
        ? {
            hookSpecificOutput: {
              hookEventName: "PreToolUse",
              permissionDecision: "deny",
              permissionDecisionReason: `Cannot modify generated Go file: ${filePath}`,
            },
          }
        : null,
    );
  });
});
