#!/usr/bin/env shellspec

# shellspec tests for Go generated file hook

# Custom matcher to check if file exists and has content
assert_file_exists_with_content() {
  file_path=${assert_file_exists_with_content:?}
  test -f "$file_path" && test -s "$file_path"
}

# Custom matcher to check if file has the generated marker
assert_has_generated_marker() {
  file_path=${assert_has_generated_marker:?}
  grep -q "^// Code generated .* DO NOT EDIT\.$" "$file_path"
}

Describe 'Go generated file hook'
  Describe 'Unit tests'
    It 'allows non-Go files' Tag unit
      test_file=$(mktemp)
      echo "some content" > "$test_file"
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh"
      The status should be success
      rm -f "$test_file"
    End

    It 'allows Go files without generated marker' Tag unit
      test_file=$(mktemp --suffix=.go)
      cat > "$test_file" <<'EOF'
package main

func main() {
    println("hello")
}
EOF
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh"
      The status should be success
      rm -f "$test_file"
    End

    It 'allows non-existent Go files' Tag unit
      test_file="/tmp/nonexistent-$(uuidgen).go"
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh"
      The status should be success
    End

    It 'blocks Go files with generated marker' Tag unit
      test_file=$(mktemp --suffix=.go)
      cat > "$test_file" <<'EOF'
// Code generated by foo. DO NOT EDIT.

package main

func main() {
    println("generated")
}
EOF
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh 2>&1"
      The status should be failure
      The output should include "Cannot modify generated Go file"
      The output should include "Update the generator code instead"
      The output should include "go generate"
      rm -f "$test_file"
    End

    It 'allows Go files with generated marker in comments after code' Tag unit
      test_file=$(mktemp --suffix=.go)
      cat > "$test_file" <<'EOF'
package main

// Code generated by foo. DO NOT EDIT.
func main() {
    println("not generated")
}
EOF
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh"
      The status should be success
      rm -f "$test_file"
    End

    It 'blocks Go files with marker before package declaration' Tag unit
      test_file=$(mktemp --suffix=.go)
      cat > "$test_file" <<'EOF'
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

type Test struct {}
EOF
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh 2>&1"
      The status should be failure
      The output should include "Cannot modify generated Go file"
      rm -f "$test_file"
    End

    It 'allows Go files with only marker and no code' Tag unit
      test_file=$(mktemp --suffix=.go)
      cat > "$test_file" <<'EOF'
// Code generated by foo. DO NOT EDIT.


EOF
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh"
      The status should be success
      rm -f "$test_file"
    End

    It 'handles empty input gracefully' Tag unit
      input='{}'
      When run sh -c "echo '$input' | ./go/check.sh"
      The status should be success
    End

    It 'blocks Go files with marker and blank lines before code' Tag unit
      test_file=$(mktemp --suffix=.go)
      cat > "$test_file" <<'EOF'
// Code generated automatically. DO NOT EDIT.


package main
EOF
      input=$(jq -n --arg file_path "$test_file" '{tool_input: {file_path: $file_path}}')
      When run sh -c "echo '$input' | ./go/check.sh 2>&1"
      The status should be failure
      rm -f "$test_file"
    End
  End

  Describe 'Integration tests'
    It 'prevents Claude from editing generated Go files' Tag integration
      test_file=$(mktemp --suffix=.go)
      abs_path=$(realpath "$test_file")

      # Create a generated Go file
      cat > "$abs_path" <<'EOF'
// Code generated by stringer. DO NOT EDIT.

package main

const Greeting = "hello"
EOF

      # Try to edit it with Claude - should fail
      permissions="Read(//$abs_path),Edit(//$abs_path)"
      When run sh -c "claude --allowedTools '$permissions' --print 'Change Greeting to goodbye in $abs_path' >/dev/null 2>&1"
      The status should be failure

      # Verify file was not modified
      The contents of file "$abs_path" should include 'const Greeting = "hello"'

      rm -f "$abs_path"
    End
  End
End
