import { describe, expect, test } from "bun:test";
import { isGeneratedFile } from "./collect";

describe("isGeneratedFile", () => {
  test("skips TypeScript declaration files by extension", () => {
    expect(isGeneratedFile("plugins/things/src/Things3.d.ts", "export const x = 1;")).toBe(true);
  });

  test("skips a file whose head announces it is generated", () => {
    expect(isGeneratedFile("a.ts", "// @generated by protoc\nexport const x = 1;")).toBe(true);
    expect(isGeneratedFile("a.ts", "/* DO NOT EDIT: generated file */\nx();")).toBe(true);
  });

  test("does not exempt a hand-written file from a deep do-not-edit mention", () => {
    const source = `${"x();\n".repeat(400)}// do not edit this line by hand`;
    expect(isGeneratedFile("a.ts", source)).toBe(false);
  });

  test("keeps an ordinary source file", () => {
    expect(isGeneratedFile("a.ts", "// a real comment\nexport function f() {}")).toBe(false);
  });
});
