import { describe, expect, test } from "bun:test";
import { isGeneratedFile } from "./collect";

describe("isGeneratedFile", () => {
  const deepMention = `${"x();\n".repeat(400)}// do not edit this line by hand`;

  test.each<[string, string, string, boolean]>([
    ["declaration file", "plugins/things/src/Things3.d.ts", "export const x = 1;", true],
    ["generated line-comment header", "a.ts", "// @generated by protoc\nexport const x = 1;", true],
    ["generated block-comment header", "a.ts", "/* DO NOT EDIT: generated file */\nx();", true],
    ["deep do-not-edit mention doesn't exempt a hand-written file", "a.ts", deepMention, false],
    ["ordinary source file", "a.ts", "// a real comment\nexport function f() {}", false],
  ])("%s", (_name, path, source, expected) => {
    expect(isGeneratedFile(path, source)).toBe(expected);
  });
});
